### ISSUE TITLE
MISSING FILES for v2.4.s4 board ! GNU LICENSE VIOLATION

### ISSUE THREAD

**Issue by edgelgithub** [CrealityOfficial/Ender-2-Pro#23]
Apparently not complete source.
refer to https://github.com/CrealityOfficial/Ender-2-Pro/blob/MCU_HDSC/workspace/firmware.uvoptx

ALso the firmware.uvprojx is missing. Project file for Keil
But the workaround is to use the deleted .uvprojx from the commit
then refer to https://github.com/CrealityOfficial/Ender-2-Pro/blob/MCU_HDSC/workspace/firmware.uvoptx
to add the source files.
All good the source group appear on Keil but many of the files are missing.
ie
component folde

- sdio_hal.cpp
- sd_card.c
- adc.c
etc....
 refer to https://github.com/CrealityOfficial/Ender-2-Pro/blob/MCU_HDSC/workspace/firmware.uvoptx for the files in the group name component,framework,main

**Comment by The-300lb-Gorilla** [comment]
You do realize that you will be chasing Creality for at least 2 years or more just to get them to release all the files. This is why I no longer buy factory machines. The last 3 235x235x275mm 3D Printers I have built from scratch. I did recycle a Aquila C2 x-axis and hot end carriage on my last build.
