### ISSUE TITLE
Missing Source Code and Configuration Files

### ISSUE THREAD

**Issue by ghost** [CrealityOfficial/Ender-2-Pro#4]
Follow up: Received email linking me to this repository, I told Creality Online Store That The Files Are Not Up To Date.

10-28-2022 2:21pm EST USA

Copy of their email response:
For source code, you can find it in this community:
https://github.com/CrealityOfficial
If not, you can also give feedback in it.

Kind regards 
Customer Service Department
----------------------------------------------------------------------------------------------------------------------------------------------
Missing Source Code for firmware release: 4.2.3CRTouch - Ender-2 ProMarlin2.0.6.1X165HW [Released 8-17-2022]
Missing Source Code for firmware release: Ender-2pro-hw2.4.s4xx-sw2.2.36_165 [Released 8-17-2022]
These two firmware versions were released by Creality Store Online.
From this Google Drive Repository:
https://drive.google.com/drive/folders/1ksIpQG3mgXbeyhuX-SBMAE3mRGWSbLhr
As per the License, please provide the configuration files and the source code for these two releases.

Thank You for you assistance in this matter.
Sincerely,
The 300lb Gorilla & The Wandering Artist LLC
CrealityEnder2Pro
The Gorilla Tech Programming Group

**Comment by The-300lb-Gorilla** [comment]
Quoted Text from an email send by the Gorilla Tech Programming Group, LLC

to Creality, and Creality-US

Source code for 4.2.3 Mainboard firmware is in their Repository here:https://github.com/CrealityOfficial/Ender-2-ProThis is the v4.2.3 mainboard in older Creality Ender 2 Pro 3D Printers.

However, You have been using a different mainboard, with the HDSC CPU in newer Creality Ender 2 Pros. The source code has not been released for the HDSC CPU Mainboard, and it is NOWHERE in the link provided in the repository on github in the issues tab. Under the licensing Agreement, you are REQUIRED to release the firmware source code, not just the firmware. As you can see, Link: https://www.th3dstudio.com/3d-printer-gpl-violation-list/Respectfully,you 

have already been LISTED AS NON COMPLIANT by TH3DStudios.com for non compliance of the License. 

They are HIGHLY Recommending that people NOT buy Creality Products on their site, and they have a huge you tube following and are leaders in the 3D Printing community. 

We at the Gorilla Tech Programming Group, LLC are requesting that you release the source code for the HDSC CPU Mainboard, for firmware version:

 Ender-2pro-hw2.4.s4xx-sw2.2.36_165 [Released 8-17-2022]. 

Failure to do so will mean you are in violation of the licensing agreement. 
![v2 4 s4-HDSC32F460-CPU-Ender-2-Pro-Mainboard](https://user-images.githubusercontent.com/118843387/203602250-0198bd5f-9862-4cd9-8bc3-5f1e4eaae411.jpeg)


Other 3D Printing Community Leaders on social media and on you tube, are preparing a boycott of Creality Products sold by Creality and Creality-US on Amazon, and at your official site. 

Amazon has been made aware of your selling products on their site in violation of the licensing agreement. They are currently investigating the matter.

In closing, please, just release the source code for the newer HDSC CPU mainboards using the firmware: Ender-2pro-hw2.4.s4xx-sw2.2.36_165 [Released 8-17-2022]
![v2 4 s4-HDSC32F460-CPU-Ender-2-Pro-Mainboard](https://user-images.githubusercontent.com/118843387/203602250-0198bd5f-9862-4cd9-8bc3-5f1e4eaae411.jpeg)

Dropping firmware releases on a Google Drive with a link is not the way to resolve this matter. Again, PLEASE release the SOURCE CODE for this version of the firmware.

Thank You 

Sincerely,

Gorilla Tech Programming Group, LLC

**Comment by The-300lb-Gorilla** [comment]
This is the older v4.2.3 mainboard that the source code was released for:
![v4 2 3- CPU-Type STM32F103RET6 Mainbaord - older](https://user-images.githubusercontent.com/118843387/203602599-b02e3625-01da-445f-a499-f8497efb2771.jpg)

**Comment by The-300lb-Gorilla** [comment]
And this is the New HDSC CPU Mainboard you have not released the source code for:
![v2 4 s4-HDSC32F460-CPU-Ender-2-Pro-Mainboard](https://user-images.githubusercontent.com/118843387/203602824-4c1d72ab-91a8-4266-88e0-32e1bb6fade0.jpeg)

**Comment by CrealityTech** [comment]
we had publish it ,enjoy it
