### ISSUE TITLE
HDSC32F460 CPU (MISSING SOURCE CODE)

### ISSUE THREAD

**Issue by The-300lb-Gorilla** [CrealityOfficial/Ender-2-Pro#5]
Source code for 4.2.3 Mainboard firmware is in their Repository here:https://github.com/CrealityOfficial/Ender-2-ProThis is the v4.2.3 mainboard in older Creality Ender 2 Pro 3D Printers.

However, You have been using a different mainboard, with the HDSC CPU in newer Creality Ender 2 Pros. The source code has not been released for the v2 4 s4-HDSC32F460-CPU Mainboard, and it is NOWHERE in the link provided in the repository on github in the issues tab. Under the licensing Agreement, you are REQUIRED to release the firmware source code, not just the firmware. As you can see, Link: https://www.th3dstudio.com/3d-printer-gpl-violation-list/Respectfully,you 
have already been LISTED AS NON COMPLIANT by TH3DStudios.com for non compliance of the License. 
They are HIGHLY Recommending that people NOT buy Creality Products on their site, and they have a huge you tube following and are leaders in the 3D Printing community. 

We at the Gorilla Tech Programming Group, LLC are requesting that you release the source code for the v2 4 s4-HDSC32F460-CPU Mainboard, for firmware version:  Ender-2pro-hw2.4.s4xx-sw2.2.36_165 [Released 8-17-2022]. 

Failure to do so will mean you are in violation of the licensing agreement. 
![v2 4 s4-HDSC32F460-CPU-Ender-2-Pro-Mainboard](https://user-images.githubusercontent.com/118843387/203602250-0198bd5f-9862-4cd9-8bc3-5f1e4eaae411.jpeg)

Amazon has been made aware of your selling products on their site in violation of the licensing agreement. They are currently investigating the matter.

**Comment by CrealityTech** [comment]
we had publish it ,enjoy it
